export const REQUEST_STATUS = {
  CREATED: 'CREATED',
  SENT: 'SENT',
  ACKED: 'ACKED',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  UNVERIFIED: 'UNVERIFIED',
  TIMED_OUT: 'TIMED_OUT',
  DISPUTED: 'DISPUTED'
};

export const ERROR_DOMAIN = {
  AUTH: 'AUTH',
  CONTRACT: 'CONTRACT',
  EXEC: 'EXEC',
  RESULT: 'RESULT',
  DELIVERY: 'DELIVERY',
  TEMPLATE: 'TEMPLATE',
  PLATFORM: 'PLATFORM'
};
